<?php
echo'<header>
    <h1>LSCL Home Page</h1>
    <img src="images/logo.jpg" alt="LSCL Logo" class="logo" />
    <nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="login.php">Management</a></li>
        </ul>
    </nav>
</header>'
?>