    <?php
        echo "<table border='1' cellpadding='5'>";
        echo "<tr><th>EOInumber</th><th>Job Reference number</th><th>First name</th><th>Middle name</th><th>Last name</th><th>Skill 1</th><th>Skill 2</th>
        <th>Skill 3</th><th>Email address</th><th>Phone number</th><th>State</th><th>Street address</th><th>Suburb/town</th><th>Postcode</th><th>DOB</th>
        <th>Gender</th><th>Willing to Move</th><th>Other Skill</th><th>Status</th><th></th></tr>";
    ?>